export const categories = [
  ["Wrench", "Screwdriver", "Hammer", "Pliers", "Drill"], // All words are tools used for mechanical work (nouns)
  ["Adorable", "Charming", "Lovely", "Cute", "Endearing"], // All words describe pleasant or attractive qualities (adjectives)
  ["Cook", "Bake", "Grill", "Sauté", "Roast"], // All words describe methods of preparing food (verbs)
  ["Tiger", "Lion", "Jaguar", "Leopard", "Cheetah"], // All words are types of big cats (nouns)
  ["Unpredictable", "Erratic", "Volatile", "Fickle", "Inconsistent"], // All words describe a lack of predictability (adjectives)
  ["Piano", "Violin", "Cello", "Guitar", "Harp"], // All words are types of string instruments (nouns)
  ["Navigate", "Direct", "Guide", "Steer", "Pilot"], // All words relate to controlling the movement of something (verbs)
  ["Desolate", "Barren", "Empty", "Lonely", "Forsaken"], // All words describe a lack of inhabitants or activity (adjectives)
  ["Doctor", "Nurse", "Surgeon", "Paramedic", "Physician"], // All words are types of medical professionals (nouns)
  ["Bright", "Gleaming", "Luminous", "Radiant", "Shining"], // All words describe strong light or brightness (adjectives)
  ["Tablet", "Laptop", "Smartphone", "Computer", "E-reader"], // All words describe electronic devices (nouns)
  ["Perform", "Act", "Execute", "Deliver", "Present"], // All words relate to carrying out actions or tasks (verbs)
  ["Ardent", "Passionate", "Fervent", "Zealous"], // All words describe strong feelings or enthusiasm (adjectives)
  ["Architect", "Builder", "Engineer", "Draftsman", "Designer"], // All words are professionals involved in construction or design (nouns)
  ["Turbulent", "Stormy", "Rough", "Choppy", "Unsettled"], // All words describe turbulent or unstable conditions (adjectives)
  ["Debate", "Discuss", "Argue", "Deliberate", "Negotiate"], // All words involve exchanging ideas or opinions (verbs)
  ["Serene", "Calm", "Tranquil", "Peaceful", "Quiet"], // All words describe a state of calmness (adjectives)
  ["Keyboard", "Mouse", "Monitor", "Printer", "Scanner"], // All words are peripheral devices for computers (nouns)
  ["Annoy", "Irritate", "Disturb", "Bother", "Agitate"], // All words describe causing discomfort or inconvenience (verbs)
  ["Brilliant", "Genius", "Clever", "Smart", "Intelligent"], // All words describe high levels of intellect or ability (adjectives)
  ["Bicycle", "Scooter", "Skateboard", "Rollerblades", "Segway"], // All words are types of personal transportation devices (nouns)
  ["Endure", "Withstand", "Survive", "Persist", "Overcome"], // All words relate to enduring or overcoming challenges (verbs)
  ["Mysterious", "Enigmatic", "Cryptic", "Puzzling", "Intriguing"], // All words describe something difficult to understand (adjectives)
  ["Jacket", "Coat", "Sweater", "Vest", "Blazer"], // All words are types of outerwear garments (nouns)
  ["Scream", "Shout", "Yell", "Roar", "Howl"], // All words describe loud vocal expressions (verbs)
  ["Ancient", "Historic", "Old", "Antique", "Timeless"], // All words describe something with a long history (adjectives)
  ["Hiking", "Camping", "Fishing", "Biking", "Climbing"], // All words describe outdoor recreational activities (nouns)
  ["Sculpt", "Carve", "Chisel", "Shape"], // All words relate to forming or creating shapes (verbs)
  ["Warm", "Cozy", "Comfortable", "Heated", "Snug"], // All words describe a pleasant level of warmth (adjectives)
  ["Thrive", "Flourish", "Prosper", "Grow"], // All words relate to successful development or progress (verbs)
  ["Dull", "Blunt", "Tired", "Flat", "Unexciting"], // All words describe a lack of sharpness or interest (adjectives)
  ["Notebook", "Journal", "Pad", "Planner", "Diary"], // All words are types of bound writing surfaces (nouns)
  ["Energetic", "Dynamic", "Lively", "Active"], // All words describe high levels of energy or activity (adjectives)
  ["Jungle", "Forest", "Rainforest", "Woodland", "Thicket"], // All words are types of dense, wooded environments (nouns)
  ["Sleek", "Polished", "Elegant", "Smooth"], // All words describe something with a refined or attractive appearance (adjectives)
  ["System", "Network", "Framework", "Structure", "Model"], // All words describe organized sets or arrangements (nouns)
  ["Opulent", "Luxurious", "Sumptuous", "Extravagant", "Rich"], // All words describe high levels of luxury or wealth (adjectives)
  ["Conference", "Seminar", "Workshop", "Symposium", "Summit"], // All words are types of professional gatherings or meetings (nouns)
  ["Sketch", "Draw", "Outline", "Illustrate", "Design"], // All words relate to creating visual representations (verbs)
  ["Curious", "Inquisitive", "Eager", "Questioning", "Interested"], // All words describe a desire for knowledge or information (adjectives)
  ["Palette", "Canvas", "Easel", "Brush", "Pigment"], // All words are tools or materials used in painting (nouns)
  ["Accelerate", "Speed", "Boost", "Hasten", "Quick"], // All words relate to increasing speed or pace (verbs)
  ["Delicate", "Fragile", "Brittle", "Tender", "Frail"], // All words describe something that is easily damaged or broken (adjectives)
  ["Calculate", "Compute", "Measure", "Estimate"], // All words relate to determining quantities or values (verbs)
  ["Pillow", "Blanket", "Comforter", "Sheet", "Duvet"], // All words are items used for bedding or sleep (nouns)
  ["Inspire", "Motivate", "Encourage", "Stimulate", "Influence"], // All words relate to stimulating action or emotion (verbs)
  ["Carpet", "Rug", "Mat", "Runner", "Tapestry"], // All words describe types of floor coverings (nouns)
  ["Analyze", "Examine", "Scrutinize", "Investigate", "Assess"], // All words relate to studying something closely (verbs)
  ["Criminal", "Offender", "Suspect", "Perpetrator", "Lawbreaker"], // All words describe individuals involved in illegal activities (nouns)
  ["Hurdle", "Barrier", "Obstacle", "Challenge", "Impediment"], // All words describe things that obstruct progress (nouns)
  ["Museum", "Gallery", "Exhibition", "Showcase", "Collection"], // All words are related to places or events for displaying art or artifacts (nouns)
  // TODO: Go through the rest of the categories and eliminate overlaps
  //
  // ["Empower", "Enable", "Authorize", "Facilitate", "Equip"], // All words relate to giving power or resources (verbs)
  // ["Opera", "Symphony", "Sonata", "Concerto", "Rhapsody"], // All words are types of classical music compositions (nouns)
  // ["Champion", "Victim", "Winner", "Contender", "Participant"], // All words describe roles in a competition or contest (nouns)
  // ["Excite", "Thrill", "Arouse", "Stimulate", "Energize"], // All words relate to causing strong feelings or reactions (verbs)
  // ["Grand", "Majestic", "Splendid", "Regal", "Impressive"], // All words describe something with grandeur or magnificence (adjectives)
  // ["Scientist", "Biologist", "Chemist", "Physicist", "Researcher"], // All words describe professionals in scientific fields (nouns)
  // ["Resolve", "Decide", "Determine", "Conclude", "Choose"], // All words relate to making decisions or finding solutions (verbs)
  // ["Sparse", "Scattered", "Thin", "Few", "Isolated"], // All words describe something with few elements or occurrences (adjectives)
  // ["Instrument", "Tool", "Device", "Apparatus", "Gadget"], // All words describe objects used for specific purposes (nouns)
  // ["Collaborate", "Cooperate", "Contribute", "Partner", "Assist"], // All words relate to working together or helping (verbs)
  // ["Photograph", "Snapshot", "Picture", "Image", "Portrait"], // All words describe types of visual representations captured by cameras (nouns)
  // ["Spacious", "Vast", "Expansive", "Wide", "Broad"], // All words describe large or open areas (adjectives)
  // ["Bacteria", "Virus", "Fungi", "Protozoa", "Microbe"], // All words describe microorganisms (nouns)
  // ["Vibrant", "Colorful", "Vivid"], // All words describe strong and lively colors or light (adjectives)
  // ["Puzzle", "Riddle", "Conundrum", "Enigma", "Brainteaser"], // All words describe problems requiring thought to solve (nouns)
  // ["Optimize", "Enhance", "Refine", "Improve", "Upgrade"], // All words relate to making something better (verbs)
  // ["Rustic", "Quaint", "Countryside", "Old-fashioned"], // All words describe traditional or rural qualities (adjectives)
  // ["Gadget", "Device", "Apparatus", "Instrument", "Tool"], // All words are types of objects used for specific functions (nouns)
  // ["Communicate", "Transmit", "Relay", "Convey", "Disseminate"], // All words relate to sending information or messages (verbs)
  // ["Unusual", "Unique", "Rare", "Strange", "Exceptional"], // All words describe something out of the ordinary (adjectives)
  // ["Chair", "Table", "Sofa", "Couch", "Bench"], // All words are types of furniture (nouns)
  // ["Transform", "Convert", "Change", "Alter", "Modify"], // All words relate to making changes to something (verbs)
  // ["Book", "Magazine", "Journal", "Newspaper", "Article"], // All words are types of written publications (nouns)
  // ["Imposing", "Grand", "Majestic", "Dignified", "Statuesque"], // All words describe something with a commanding presence (adjectives)
  // ["Artist", "Musician", "Painter", "Sculptor", "Writer"], // All words describe people involved in creative work (nouns)
  // ["Energize", "Stimulate", "Invigorate", "Excite", "Revitalize"], // All words relate to increasing energy or enthusiasm (verbs)
  // ["Clarify", "Explain", "Elucidate", "Illuminate", "Define"], // All words relate to making something clear or understandable (verbs)
  // ["Durable", "Sturdy", "Robust", "Resilient", "Tough"], // All words describe something that is strong and long-lasting (adjectives)
  // ["Camera", "Tripod", "Lens", "Flash", "Viewfinder"], // All words are parts or accessories for photography (nouns)
  // ["Modify", "Alter", "Adjust", "Change", "Revise"], // All words relate to making changes to something (verbs)
  // ["Beverage", "Drink", "Juice", "Smoothie", "Cocktail"], // All words are types of drinks (nouns)
  // ["Bureau", "Desk", "Table", "Workstation", "Counter"], // All words are types of surfaces used for work (nouns)
  // ["Exciting", "Thrilling", "Stimulating", "Invigorating", "Electrifying"], // All words describe something that causes strong feelings (adjectives)
  // ["Event", "Occasion", "Celebration", "Gathering", "Function"], // All words describe types of social or formal activities (nouns)
  // ["Vast", "Expansive", "Wide", "Immense", "Broad"], // All words describe something with a large area or scope (adjectives)
  // ["Candle", "Lamp", "Lantern", "Torch", "Lightbulb"], // All words are sources of artificial light (nouns)
  // ["Simplify", "Streamline", "Clarify", "Ease", "Facilitate"], // All words relate to making something less complicated (verbs)
  // ["Bold", "Brave", "Daring", "Courageous", "Audacious"], // All words describe a willingness to face risks (adjectives)
  // ["Library", "Archive", "Collection", "Depot", "Repository"], // All words are places or collections for storing information (nouns)
  // ["Reorganize", "Restructure", "Sort", "Arrange", "Order"], // All words relate to arranging or organizing things (verbs)
  // ["Nurturing", "Caring", "Supportive", "Protective", "Empathetic"], // All words describe providing emotional or physical support (adjectives)
  // ["Instrument", "Tool", "Device", "Apparatus", "Gadget"], // All words describe objects used for specific purposes (nouns)
  // ["Edit", "Revise", "Modify", "Update", "Correct"], // All words relate to making changes or improvements (verbs)
  // ["Fiction", "Novel", "Short story", "Tale", "Fantasy"], // All words describe genres or types of imaginative writing (nouns)
  // ["Collaborate", "Work", "Join", "Partner", "Unite"], // All words relate to working together with others (verbs)
  // ["Complex", "Intricate", "Detailed", "Elaborate", "Complicated"], // All words describe something with many parts or details (adjectives)
  // ["Document", "Record", "File", "Report", "Memo"], // All words are types of written or recorded information (nouns)
  // ["Resilient", "Flexible", "Adaptable", "Strong", "Tough"], // All words describe the ability to withstand or adapt (adjectives)
  // ["Detector", "Sensor", "Gage", "Indicator"], // All words are devices used to measure or detect changes (nouns)
  // ["Unique", "Uncommon", "Rare", "Distinctive", "Exceptional"], // All words describe something that stands out from the norm (adjectives)
  // ["Survey", "Examination", "Analysis", "Assessment", "Review"], // All words relate to evaluating or investigating something (nouns)
  // ["Elaborate", "Develop", "Expand", "Detail", "Clarify"], // All words relate to providing more information or detail (verbs)
  // ["Spacious", "Vast", "Wide", "Roomy", "Expansive"], // All words describe having a lot of space (adjectives)
  // ["Mirror", "Lens", "Prism", "Glass", "Optics"], // All words relate to objects used in optical processes (nouns)
  // ["Dismantle", "Disassemble", "Take apart", "Deconstruct", "Unpack"], // All words relate to separating something into parts (verbs)
  // ["Gadget", "Device", "Appliance", "Tool", "Instrument"], // All words describe objects designed for specific functions (nouns)
  // ["Combine", "Merge", "Integrate", "Unite", "Blend"], // All words relate to bringing things together (verbs)
  // ["Creative", "Innovative", "Imaginative", "Inventive", "Original"], // All words describe high levels of originality and creativity (adjectives)
  // ["Ruler", "Compass", "Protractor", "Divider", "Caliper"], // All words are tools used for measurement and drawing (nouns)
  // ["Vehicle", "Automobile", "Car", "Truck", "Motorcycle"], // All words describe modes of personal transportation (nouns)
  // ["Organize", "Arrange", "Sort", "Categorize", "Systematize"], // All words relate to structuring or ordering items (verbs)
  // ["Pyramid", "Sphere", "Cube", "Cone", "Cylinder"], // All words are geometric shapes (nouns)
  // ["Familiar", "Recognizable", "Known", "Accustomed", "Unusual"], // All words describe the degree to which something is known or typical (adjectives)
  // ["Painter", "Sculptor", "Artist", "Illustrator", "Photographer"], // All words describe individuals involved in creative visual arts (nouns)
  // ["Compile", "Gather", "Collect", "Assemble", "Accumulate"], // All words relate to bringing together items or information (verbs)
  // ["Aquarium", "Terrarium", "Vivarium", "Tank", "Enclosure"], // All words are types of containers for living organisms (nouns)
  // ["Facilitate", "Aid", "Assist", "Support", "Help"], // All words relate to providing assistance or making processes easier (verbs)
  // ["Ecosystem", "Biome", "Habitat", "Environment", "Niche"], // All words describe ecological systems or environments (nouns)
  // ["Neglect", "Overlook", "Disregard", "Ignore", "Dismiss"], // All words relate to failing to pay attention to something (verbs)
  // ["Clothing", "Apparel", "Garments", "Attire", "Outfit"], // All words describe items worn on the body (nouns)
  // ["Organize", "Arrange", "Coordinate", "Sort", "Order"], // All words relate to structuring or systematizing things (verbs)
  // ["Sophisticated", "Complex", "Intricate", "Advanced", "Elaborate"], // All words describe something with many parts or details (adjectives)
  // ["Transmit", "Send", "Relay", "Dispatch", "Broadcast"], // All words relate to sending information or signals (verbs)
  // ["Crucible", "Beaker", "Flask", "Test tube", "Centrifuge"], // All words are laboratory equipment (nouns)
  // ["Toolbox", "Bag", "Case", "Container", "Kit"], // All words are items used for carrying or organizing tools (nouns)
  // ["Engage", "Participate", "Join", "Involve", "Take part"], // All words relate to taking an active role in something (verbs)
  // ["Unusual", "Strange", "Rare", "Odd", "Uncommon"], // All words describe something not typical or frequent (adjectives)
  // ["Dining", "Breakfast", "Lunch", "Dinner", "Supper"], // All words are types of meals (nouns)
  // ["Cell", "Organism", "Bacterium", "Tissue", "Organ"], // All words are biological units or structures (nouns)
  // ["Edit", "Revise", "Modify", "Update", "Correct"], // All words relate to making changes or improvements (verbs)
  // ["Sculpture", "Painting", "Drawing", "Print", "Mosaic"], // All words describe forms of visual art (nouns)
  // ["Facilitate", "Assist", "Help", "Enable", "Support"], // All words relate to providing aid or making processes easier (verbs)
  // ["Eloquent", "Articulate", "Fluent", "Persuasive", "Expressive"], // All words describe effective verbal communication (adjectives)
  // ["Island", "Peninsula", "Coast", "Bay", "Archipelago"], // All words describe geographical landforms related to water (nouns)
  // ["Device", "Gadget", "Tool", "Instrument", "Appliance"], // All words describe objects used for specific functions (nouns)
  // ["Magnify", "Enlarge", "Expand", "Increase", "Amplify"], // All words relate to making something larger or more intense (verbs)
  // ["Gym", "Fitness center", "Health club", "Exercise room", "Workout space"], // All words describe places for physical exercise (nouns)
  // ["Energize", "Revitalize", "Invigorate", "Stimulate", "Excite"], // All words relate to increasing energy or enthusiasm (verbs)
  // ["Simple", "Easy", "Straightforward", "Basic", "Clear"], // All words describe something uncomplicated or easy to understand (adjectives)
  // ["Reflect", "Mirror", "Echo", "Resonate", "Reverberate"], // All words relate to the bouncing back of sound or light (verbs)
  // ["Excited", "Thrilled", "Energized", "Aroused", "Stimulated"], // All words describe a state of heightened excitement (adjectives)
  // ["Harbor", "Port", "Dock", "Marina", "Quay"], // All words describe places for docking ships or boats (nouns)
  // ["Convey", "Express", "Transmit", "Communicate", "Articulate"], // All words relate to sending or sharing information (verbs)
  // ["Data", "Information", "Statistics", "Facts", "Figures"], // All words are types of quantitative or factual content (nouns)
  // ["Calibrate", "Adjust", "Set", "Fine-tune", "Modify"], // All words relate to making precise changes (verbs)
  // ["Room", "Space", "Area", "Zone", "Section"], // All words describe parts of a larger space or area (nouns)
  // ["Develop", "Create", "Form", "Build", "Construct"], // All words relate to making or putting something together (verbs)
  // ["Workstation", "Desk", "Table", "Counter", "Workspace"], // All words are surfaces or areas used for work (nouns)
  // ["Excitement", "Thrill", "Elation", "Euphoria", "Enthusiasm"], // All words describe high levels of emotional arousal (nouns)
  // ["Conclude", "Complete", "Finish", "Close", "Wrap up"], // All words relate to bringing something to an end (verbs)
  // ["Inventive", "Creative", "Innovative", "Original", "Imaginative"], // All words describe high levels of originality and creativity (adjectives)
  // ["Intense", "Strong", "Powerful", "Vivid", "Deep"], // All words describe something with a high degree of force or impact (adjectives)
  // ["Idea", "Concept", "Notion", "Thought", "Theory"], // All words describe abstract mental representations (nouns)
  // ["Adapt", "Adjust", "Modify", "Change", "Revise"], // All words relate to making alterations (verbs)
  // ["Journey", "Trip", "Excursion", "Voyage", "Adventure"], // All words describe types of travel or exploration (nouns)
  // ["Transform", "Change", "Alter", "Modify", "Reform"], // All words relate to making changes to something (verbs)
  // ["Innovative", "Cutting-edge", "Advanced", "Novel", "Pioneering"], // All words describe high levels of newness or advancement (adjectives)
  // ["Capture", "Record", "Photograph", "Snap", "Film"], // All words relate to taking visual representations (verbs)
  // ["Grand", "Majestic", "Impressive", "Regal", "Stately"], // All words describe something with a grand appearance (adjectives)
  // ["Collaborate", "Cooperate", "Team up", "Join forces", "Work together"], // All words relate to working jointly with others (verbs)
  // ["Sturdy", "Durable", "Robust", "Resilient", "Tough"], // All words describe something that is strong and able to withstand wear (adjectives)
  // ["Spectacular", "Amazing", "Incredible", "Stunning", "Astonishing"], // All words describe something that is impressive or awe-inspiring (adjectives)
  // ["Instrument", "Device", "Tool", "Apparatus", "Gadget"], // All words are types of objects used for specific functions (nouns)
  // ["Simplify", "Clarify", "Streamline", "Facilitate", "Ease"], // All words relate to making something easier or clearer (verbs)
  // ["Healthy", "Fit", "Well", "Strong", "Robust"], // All words describe a state of good physical condition (adjectives)
  // ["Creative", "Innovative", "Imaginative", "Inventive", "Original"], // All words describe high levels of originality and creativity (adjectives)
  // ["Bureau", "Desk", "Counter", "Workstation", "Table"], // All words are types of surfaces used for work or organization (nouns)
  // ["Grand", "Majestic", "Impressive", "Regal", "Stately"], // All words describe something with grandeur or magnificence (adjectives)
  // ["Transform", "Change", "Alter", "Modify", "Revise"], // All words relate to making changes to something (verbs)
  // ["Decorate", "Embellish", "Adorn", "Ornament", "Enhance"], // All words describe adding beauty or detail (verbs)
  // ["Unique", "Distinctive", "Exceptional", "Uncommon", "Rare"], // All words describe something that stands out or is not ordinary (adjectives)
  // ["Exciting", "Thrilling", "Stimulating", "Invigorating", "Electrifying"], // All words describe something that causes strong feelings (adjectives)
  // ["Document", "Record", "File", "Report", "Log"], // All words are types of written or recorded information (nouns)
  // ["Transform", "Change", "Alter", "Modify", "Adjust"], // All words relate to making changes to something (verbs)
  // ["Creative", "Innovative", "Imaginative", "Original", "Inventive"], // All words describe high levels of originality and creativity (adjectives)
  // ["Adjust", "Modify", "Alter", "Change", "Revise"], // All words relate to making changes or improvements (verbs)
  // ["Grand", "Majestic", "Imposing", "Stately", "Regal"], // All words describe something with a grand or impressive appearance (adjectives)
  // ["Precise", "Exact", "Accurate", "Detailed", "Specific"], // All words describe a high level of correctness or exactness (adjectives)
  // ["Illuminate", "Light", "Brighten", "Shine", "Radiate"], // All words relate to providing light or making something brighter (verbs)
  // ["Precise", "Accurate", "Exact", "Detailed", "Meticulous"], // All words describe high levels of correctness and attention to detail (adjectives)
  // ["Concept", "Idea", "Notion", "Theory", "Belief"], // All words describe abstract mental representations or thoughts (nouns)
  // ["Concept", "Idea", "Theory", "Notion", "Belief"], // All words describe abstract mental representations or thoughts (nouns)
  // ["Unique", "Distinctive", "Exceptional", "Unusual", "Uncommon"], // All words describe something that is out of the ordinary or special (adjectives)
  // ["Transform", "Change", "Alter", "Modify", "Adjust"], // All words relate to making changes to something (verbs)
  // ["Journey", "Expedition", "Adventure", "Trip", "Voyage"], // All words describe types of travel or exploration (nouns)
  // ["Innovative", "Creative", "Imaginative", "Inventive", "Original"], // All words describe high levels of originality and creativity (adjectives)
  // ["Complicated", "Complex", "Intricate", "Detailed", "Elaborate"], // All words describe something with many parts or details (adjectives)
  // ["Collaborate", "Partner", "Join", "Cooperate", "Work together"], // All words relate to working together with others (verbs)
  // ["Traditional", "Classic", "Conventional", "Timeless", "Heritage"], // All words describe something that has a long history or established form (adjectives)
  // ["Instrument", "Device", "Tool", "Apparatus", "Gadget"], // All words describe objects designed for specific functions (nouns)
  // ["Visualize", "Imagine", "Envision", "Picture", "Conceptualize"], // All words relate to creating mental images or ideas (verbs)
  // ["Innovative", "Original", "Creative", "Inventive", "Groundbreaking"], // All words describe high levels of newness or advancement (adjectives)
  // ["Timeless", "Classic", "Enduring", "Evergreen", "Traditional"], // All words describe something that remains relevant or stylish over time (adjectives)
  // ["Interactive", "Engaging", "Participatory", "Immersive", "Involving"], // All words describe something that actively involves the participant (adjectives)
  // ["Innovative", "Creative", "Original", "Cutting-edge", "Novel"], // All words describe high levels of newness or advancement (adjectives)
  // ["Sculpture", "Painting", "Drawing", "Print", "Collage"], // All words describe forms of visual art (nouns)
  // ["Conceptualize", "Visualize", "Envision", "Imagine"], // All words relate to forming or creating mental images or ideas (verbs)
  // ["Enlighten", "Educate", "Illuminate", "Inform", "Instruct"], // All words relate to providing knowledge or clarity (verbs)
  // ["Splendid", "Magnificent", "Grand", "Impressive"], // All words describe something that is impressive or awe-inspiring (adjectives)
  // ["Envision", "Imagine", "Visualize", "Picture", "Conceptualize"], // All words relate to creating mental images or ideas (verbs)
  // ["Pioneering", "Innovative", "Groundbreaking", "Trailblazing", "Avant-garde"], // All words describe high levels of newness or advancement (adjectives)
  // ["Sophisticated", "Complex", "Intricate", "Refined", "Advanced"], // All words describe something with a high level of detail or advancement (adjectives)
  // ["Streamline", "Simplify", "Optimize", "Facilitate", "Enhance"], // All words relate to making something more efficient or effective (verbs)
  // ["Captivating", "Enchanting", "Alluring", "Delightful"], // All words describe something that attracts or fascinates (adjectives)
  // ["Cutting-edge", "Innovative", "Pioneering", "Advanced", "State-of-the-art"], // All words describe high levels of newness or advancement (adjectives)
  // ["Artistic", "Creative", "Imaginative", "Inventive", "Original"], // All words describe high levels of creativity and artistic flair (adjectives)
  // ["Modern", "Contemporary", "Current", "Up-to-date", "Recent"], // All words describe something that is in line with present trends or times (adjectives)
  // ["Inventive", "Creative", "Innovative", "Original", "Imaginative"], // All words describe high levels of creativity and originality (adjectives)
  // ["Intricate", "Complex", "Detailed", "Elaborate", "Complicated"], // All words describe something with many parts or details (adjectives)
  // ["Collaborate", "Partner", "Join", "Work together", "Cooperate"], // All words relate to working together with others (verbs)
];
