export const categories = [
  ["Klucz", "Śrubokręt", "Młot", "Szczypce", "Wiertło"],
  ["Uroczy", "Czarujący", "Słodki", "Cudowny"],
  ["Gotować", "Piec", "Grillować", "Smażyć", "Opiekać"],
  ["Tygrys", "Lew", "Jaguar", "Lampart", "Gepard"],
  ["Nieprzewidywalny", "Zmienny", "Kapryśny", "Niestabilny"],
  ["Piano", "Skrzypce", "Wiolonczela", "Gitara"],
  ["Nawigować", "Kierować", "Prowadzić", "Sterować"],
  ["Opustoszały", "Jałowy", "Pustynny", "Samotny"],
  ["Lekarz", "Pielęgniarz", "Chirurg", "Ratownik"],
  ["Jasny", "Błyszczący", "Lśniący", "Promienny"],
  ["Tablet", "Laptop", "Smartfon", "Komputer"],
  ["Wykonywać", "Działać", "Realizować", "Prezentować"],
  ["Gorliwy", "Pasjonat", "Entuzjastyczny"],
  ["Architekt", "Budowniczy", "Inżynier", "Projektant"],
  ["Burzliwy", "Sztormowy", "Niespokojny", "Wstrząsający"],
  ["Debatować", "Dyskutować", "Kłócić się", "Negocjować"],
  ["Spokojny", "Cichy", "Zrelaksowany"],
  ["Klawiatura", "Myszka", "Monitor", "Drukarka"],
  ["Denerwować", "Irrytować", "Niepokoić", "Wkurzać"],
  ["Genialny", "Clever", "Inteligentny", "Bystry"],
  ["Rower", "Hulajnoga", "Deskorolka", "Rolki"],
  ["Wytrzymać", "Przetrwać", "Znieść", "Pokonać"],
  ["Tajemniczy", "Zagadkowy", "Intrygujący", "Sekretny"],
  ["Kurtka", "Płaszcz", "Sweter", "Kamizelka"],
  ["Krzyczeć", "Wrzeszczeć", "Wołać", "Ryczeć"],
  ["Starożytny", "Zabytkowy", "Antyczny", "Historyczny"],
  ["Wędrówki", "Obozowanie", "Wędrówka", "Wspinaczka"],
  ["Rzeźbić", "Klepać", "Kształtować", "Formować"],
  ["Ciepły", "Przytulny", "Wygodny", "Zaciszny"],
  ["Rozwijać się", "Rozkwitać", "Proszę", "Wzbogacać"],
  ["Tępy", "Znużony", "Płaski", "Niezajmujący"],
  ["Notatnik", "Dziennik", "Zeszyt", "Planer"],
  ["Energetyczny", "Dynamiczny", "Żywy", "Aktywny"],
  ["Dżungla", "Las", "Puszcza", "Zarośla"],
  ["Gładki", "Elegancki", "Polerowany", "Stylowy"],
  ["System", "Sieć", "Struktura", "Model"],
  ["Luksusowy", "Wystawny", "Szykowny", "Bogaty"],
  ["Konferencja", "Seminarium", "Warsztat", "Zjazd"],
  ["Szkicować", "Rysować", "Ilustrować", "Kreślić"],
  ["Ciekawski", "Dociekliwy", "Zainteresowany", "Niecierpliwy"],
  ["Paleta", "Płótno", "Sztaluga", "Pędzel"],
  ["Przyspieszać", "Zwiększać", "Wzmocnić", "Szybkość"],
  ["Delikatny", "Kruche", "Wrażliwy", "Łagodny"],
  ["Obliczać", "Mierzyć", "Szacować", "Liczyć"],
  ["Poduszka", "Koc", "Kołdra", "Poszwa"],
  ["Inspirować", "Motywować", "Zachęcać", "Stymulować"],
  ["Dywan", "Wykładzina", "Maty", "Tkanina"],
  ["Analizować", "Badać", "Oceniać", "Zbadać"],
  ["Kryminalny", "Przestępca", "Podejrzany", "Sprawca"],
  ["Przeszkoda", "Wyzwanie", "Bariera", "Utrudnienie"],
  ["Muzeum", "Galeria", "Ekspozycja", "Zbiory"],
];
