import type { WordsMeaningData } from "@components/TestApp/types";

export default [
  ["Chave inglesa", "Chave de fenda", "Martelo", "Alicate", "Furadeira"],
  ["Adorável", "Encantador", "Bonito", "Fofo", "Cativante"],
  ["Cozinhar", "Assar", "Grelhar", "Refogar", "Torrar"],
  ["Tigre", "Leão", "Jaguar", "Leopardo", "Guepardo"],
  ["Imprevisível", "Errático", "Volátil", "Inconstante", "Inconsistente"],
  ["Piano", "Violino", "Violoncelo", "Guitarra", "Harpa"],
  ["Navegar", "Dirigir", "Guiar", "Conduzir", "Pilotar"],
  ["Desolado", "Árido", "Vazio", "Solitário", "Abandonado"],
  ["Médico", "Enfermeiro", "Cirurgião", "Paramédico", "Doutor"],
  ["Brilhante", "Reluzente", "Luminoso", "Radiante", "Resplandecente"],
  ["Tablet", "Notebook", "Smartphone", "Computador", "Leitor digital"],
  ["Executar", "Agir", "Realizar", "Apresentar", "Desempenhar"],
  ["Ardente", "Apaixonado", "Fervoroso", "Zeloso"],
  ["Arquiteto", "Construtor", "Engenheiro", "Desenhista", "Designer"],
  ["Turbulento", "Tempestuoso", "Agitado", "Instável", "Revolto"],
  ["Debater", "Discutir", "Argumentar", "Deliberar", "Negociar"],
  ["Sereno", "Calmo", "Tranquilo", "Pacífico", "Quieto"],
  ["Teclado", "Mouse", "Monitor", "Impressora", "Scanner"],
  ["Aborrecer", "Irritar", "Perturbar", "Incomodar", "Agitar"],
  ["Brilhante", "Gênio", "Inteligente", "Esperto", "Astuto"],
  ["Bicicleta", "Patinete", "Skate", "Patins", "Segway"],
  ["Suportar", "Resistir", "Sobreviver", "Persistir", "Superar"],
  ["Misterioso", "Enigmático", "Críptico", "Desconcertante", "Intrigante"],
  ["Jaqueta", "Casaco", "Suéter", "Colete", "Blazer"],
  ["Gritar", "Berrar", "Estrilar", "Rugir", "Uivar"],
  ["Antigo", "Histórico", "Velho", "Antiquado", "Atemporal"],
  ["Trilha", "Camping", "Pesca", "Ciclismo", "Escalada"],
  ["Esculpir", "Talhar", "Cinzelar", "Moldar"],
  ["Quente", "Aconchegante", "Confortável", "Aquecido", "Macio"],
  ["Prosperar", "Florescer", "Crescer", "Evoluir"],
  ["Sem graça", "Embotado", "Cansado", "Monótono", "Desinteressante"],
  ["Caderno", "Diário", "Bloco", "Agenda", "Planner"],
  ["Energético", "Dinâmico", "Vivo", "Ativo"],
  ["Selva", "Floresta", "Mata Atlântica", "Bosque", "Matagal"],
  ["Elegante", "Polido", "Refinado", "Suave"],
  ["Sistema", "Rede", "Estrutura", "Framework", "Modelo"],
  ["Opulento", "Luxuoso", "Suntuoso", "Extravagante", "Rico"],
  ["Conferência", "Seminário", "Workshop", "Simpósio", "Cúpula"],
  ["Esboçar", "Desenhar", "Traçar", "Ilustrar", "Projetar"],
  ["Curioso", "Inquisitivo", "Ansioso", "Questionador", "Interessado"],
  ["Paleta", "Tela", "Cavalete", "Pincel", "Pigmento"],
  ["Acelerar", "Velocidade", "Impulsionar", "Apressar", "Rápido"],
  ["Delicado", "Frágil", "Quebradiço", "Terno", "Fraco"],
  ["Calcular", "Computar", "Medir", "Estimar"],
  ["Travesseiro", "Cobertor", "Edredom", "Lençol", "Duvet"],
  ["Inspirar", "Motivar", "Encorajar", "Estimular", "Influenciar"],
  ["Carpete", "Tapete", "Capacho", "Passadeira", "Tapeçaria"],
  ["Analisar", "Examinar", "Escrutinar", "Investigar", "Avaliar"],
  ["Criminoso", "Infrator", "Suspeito", "Perpetrador", "Fora da lei"],
  ["Obstáculo", "Barreira", "Empecilho", "Desafio", "Impedimento"],
  ["Museu", "Galeria", "Exposição", "Mostra", "Coleção"],
] satisfies WordsMeaningData;
